name: CICD
on: [push]
permissions:
    contents: read
    packages: write
jobs: 
    CI:
        runs-on: ubuntu-latest
        env:
            Sln: CDTest.sln
            Configuration: Release
        steps:
            - name: 步驟 1 - 下載程式碼到執行環境
              uses: actions/checkout@v4

            - name: 步驟 2 - 安裝 .NET SDK
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 8.0.x

            - name: 步驟 3 - 還原依賴 (Restore)
              run: dotnet restore ${{ env.Sln }}

            - name: 步驟 4 - 編譯專案 (Build)
              run: dotnet build ${{ env.Sln }} --configuration ${{ env.Configuration }} --no-restore

            - name: 步驟 5 - 執行單元測試 (Test)
              run: dotnet test ${{ env.Sln }} --configuration ${{ env.Configuration }} --no-build --verbosity normal
        
            - name: 步驟 6 - 登入 GitHub 容器註冊表 (GHCR)
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: 步驟 7 - 打包並推送映像檔 (Build and Push Image)
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile
                push: true              
                tags: |
                  ghcr.io/${{ github.repository }}/web-app:latest
                  ghcr.io/${{ github.repository }}/web-app:${{ github.run_number }}
    # CD:
    #     needs: CI
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: 步驟1 
    #           uses: actions/download-artifact@v4
    #           with:
    #             name: my-web-app
    #             path: 
    
        
        
     